# Generated by rebar3_nix
{ fetchHex, fetchFromGitHub }:
{
  ranch = fetchHex {
    pkg = "ranch";
    version = "1.7.1";
    sha256 = "sha256-RR2FJ3h99xbZncNhYvygWTSRXbC2FBu9rC6o08evx9c=";
  };
  cowlib = fetchHex {
    pkg = "cowlib";
    version = "2.9.1";
    sha256 = "sha256-5BddwkCnDZlhVhYIkeHGIjjt4XKeRXQL3TgGTa1HYXA=";
  };
  lager = fetchHex {
    pkg = "lager";
    version = "3.9.1";
    sha256 = "sha256-P1m6daBKmeXxi/kcifRtzlNvg8bLQV/ibm51pivvN9w=";
  };
  cowboy = fetchHex {
    pkg = "cowboy";
    version = "2.8.0";
    sha256 = "sha256-RkPk+6dKyW1NFSx1gD3m+tCz+l3zVMca/dbL7rFfrIo=";
  };
}
